import type { ValidationOptions } from './sc-format-validation.types';

export const OPERATOR_ALIASES: Record<string, string> = {
  eq: 'eq',
  neq: 'neq',
  gt: 'gt',
  gte: 'gte',
  lt: 'lt',
  lte: 'lte',
  between: 'between',
  like: 'like',
  ilike: 'iLike',
  notlike: 'notLike',
  contains: 'contains',
  startswith: 'startsWith',
  endswith: 'endsWith',
  regex: 'regex',
  in: 'in',
  notin: 'notIn',
  any: 'any',
  all: 'all',
  size: 'size',
  isnull: 'isNull',
  isnotnull: 'isNotNull',
  exists: 'exists',
  notexists: 'notExists',
  date: 'date',
  year: 'year',
  month: 'month',
  day: 'day',
  case: 'case',
  when: 'when',
  then: 'then',
  else: 'else',
};

export const VALID_OPERATORS = [
  'eq',
  'neq',
  'gt',
  'gte',
  'lt',
  'lte',
  'between',
  'like',
  'iLike',
  'notLike',
  'contains',
  'startsWith',
  'endsWith',
  'regex',
  'in',
  'notIn',
  'any',
  'all',
  'size',
  'isNull',
  'isNotNull',
  'exists',
  'notExists',
  'date',
  'year',
  'month',
  'day',
  'case',
  'when',
  'then',
  'else',
] as const;

export const DEFAULT_VALIDATION_OPTIONS: ValidationOptions = {
  maxConditions: 50,
  maxValueLength: 1000,
  allowNestedFields: true,
  allowRelations: true,
  strictMode: false,
};

export const DISPLAY_OPERATORS = [
  'eq',
  'neq',
  'gt',
  'gte',
  'lt',
  'lte',
  'between',
  'like',
  'iLike',
  'contains',
  'startsWith',
  'endsWith',
  'in',
  'notIn',
  'any',
  'all',
  'size',
  'isNull',
  'isNotNull',
  'exists',
  'notExists',
];

export const DANGEROUS_PATTERNS = [
  {
    pattern: /('|")(\s*)(or|and)(\s*)(\d+)(\s*)=(\s*)(\d+|'(\d+)')/i,
    message: 'Potential SQL injection detected',
  },
  { pattern: /(--)/, message: 'SQL comment detected' },
  { pattern: /(;\s*drop\s+table)/i, message: 'DROP TABLE detected' },
  { pattern: /(;\s*delete\s+from)/i, message: 'DELETE FROM detected' },
  { pattern: /(union\s+select)/i, message: 'UNION SELECT detected' },
  {
    pattern: /(exec\s*\(|\s*execute\s*\(\))/i,
    message: 'EXEC command detected',
  },
  { pattern: /<script/i, message: 'XSS script tag detected' },
  { pattern: /javascript:/i, message: 'JavaScript protocol detected' },
  { pattern: /\\x[0-9a-f]{2}/i, message: 'Hex encoding detected' },
] as const;
